name: Deploy to EC2

on: [push]
  branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    setps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: cofigure aws credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: transfer files to ec2
      run: |
        scp -o StrictHostKeyChecking=no -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }}:/home/${{ secrets.EC2_USER }}/app/

    - name: SSH into ec2 and set up application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/app
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          nohup flask run --host=0.0.0.0 --port=80 &
          nohup gunicorn -w 4 -b 0.0.0.0:80 app:app &
        EOF
 